parameters:
    crevillo.productcategory.fieldType.ezproductcategory.class: Crevillo\ProductCategoryBundle\eZ\Publish\Core\FieldType\ProductCategory\Type
    crevillo.productcategory.fieldType.ezproductcategory.productcategory.class: Crevillo\ProductCategoryBundle\eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\ProductCategory

services:
    crevillo.productcategory.fieldType.ezproductcategory.class:
        parent: ezpublish.fieldType
        class: %crevillo.productcategory.fieldType.ezproductcategory.class%
        tags:
            - {name: ezpublish.fieldType, alias: ezproductcategory}

    crevillo.productcategory.fieldType.ezproductcategory.converter:
        class: %crevillo.productcategory.fieldType.ezproductcategory.converter.class%
        tags:
            - {name: ezpublish.storageEngine.legacy.converter, alias: ezproductcategory, lazy: true, callback: '::create'}
